"""empty message

Revision ID: 600f0f631b6c
Revises: 
Create Date: 2020-08-03 00:22:34.114068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600f0f631b6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色編號'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='角色名稱'),
    sa.Column('info', sa.Text(length=500), nullable=True, comment='角色其他資訊'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='角色建立時間'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='角色修改時間'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用戶編號'),
    sa.Column('username', sa.String(length=30), nullable=False, comment='用戶登入名稱'),
    sa.Column('email', sa.String(length=200), nullable=False, comment='用戶信箱'),
    sa.Column('_hash_pwd', sa.String(length=300), nullable=False, comment='用戶密碼'),
    sa.Column('rid', sa.Integer(), nullable=False, comment='用戶角色類型:1.管理者 2.主要用戶 3.被動用戶'),
    sa.Column('name', sa.String(length=30), nullable=True, comment='用戶姓名'),
    sa.Column('info', sa.Text(length=500), nullable=True, comment='用戶其他資訊'),
    sa.Column('create_at', sa.DateTime(), nullable=True, comment='用戶建立時間'),
    sa.Column('update_at', sa.DateTime(), nullable=True, comment='用戶修改時間'),
    sa.ForeignKeyConstraint(['rid'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
